### PR TITLE
Fix cmake:2.30 build

### PR DESCRIPTION
**Pull request by bartoszek**
When initialize submodule with `git submodule update --init --remote`  `env:{os:Linux,dist:Arch,cmake:2.30}`
It ended with submodule path containing `git bare mirror` instead of `git clone` of submodule.
This renders `GetGitRevisionDescription.cmake` broken as it search for `.git` directory to determine `git:revision`

As a fix I would propose we first check if `HEAD` file exist in submodule directory:
* if yes submodule is a bare mirror and we continue from there.
* if not submodule is a clone and we look for `.git` starting there.

### CODE REVIEW

**Comment by vukics** [comment]
Thanks a lot! I realize that I do not understand how this `GetGitRevisionDescription` mechanism works, so I’m going to trust you in this one.

**Comment by bartoszek** [comment]
`GetGitRevisionDescription` is just an overcomplicated way to call `git rev-parse HEAD`. Perhaps it was somehow necessary for overcoming limitations of previous version version of `git` but now it is just redundant and should be dropped in favor of just calling `git rev-parse --short=6 HEAD` in `$CMAKE_CURRENT_SOURCE_DIR` and in `$CMAKE_CURRENT_SOURCE_DIR/blitz` to get CPPQED_GIT_SHA1 and BLITZ_GIT_SHA1 and put it in [cppqedGitSHA1.cc](https://github.com/vukics/cppqed/blob/Development/cmake/cppqedGitSHA1.cc.in) and [blitzGitSHA1.cc.in](https://github.com/vukics/blitz/blob/22e6944934ab3fd21458215125ffdc0527553e12/cmake/blitzGitSHA1.cc.in) respectivly.

`GetGitRevisionDescription` originated from [rpavlik/cmake-modules](https://github.com/rpavlik/cmake-modules) repository and [almost half the of reported issues refferes to it (－‸ლ) ](https://github.com/rpavlik/cmake-modules/issues?q=GetGitRevisionDescription)

For example check how [blender doing same thing.](https://developer.blender.org/diffusion/B/browse/master/build_files/cmake/buildinfo.cmake)

**Comment by vukics** [comment]
@bartoszek Thanks for the info! I would be more than happy to drop `GetGitRevisionDescription` in favor of something that `git` can do out of the box. So please feel free to implement it, and I’d be happy to merge.

**Comment by rpavlik** [comment]
Have you updated to the latest version of that script? It's pretty robust by now since as you noticed, it's pretty widely used... (all the related issues in the repo are closed except for one asking for extra docs) I'd be happy to upstream your patch if I understood what it was doing - it looks like a fancy way of commenting out the finding of the workdir since GIT_DIR doesn't get used later?

(Also it looks like you might be using some new submodule functionality I hadn't heard of before, so I'll have to dig into it)

Git doing things like "hey look, add workdirs" or moving the metadata for submodules or... affects the ability for the script to find a file to use as a "trigger" to re-cmake. There are functions in the module that don't require that and are thus more robust, but may not trigger a re-cmake after a commit, branch change, etc. The "overcomplicated" part is finding some file that will update when the meaning of HEAD changes, and telling CMake to re-configure when that changes.

**Comment by vukics** [comment]
@rpavlik Thanks for the valuable information, it’s important to know that the re-cmake-triggering functionality is the most complicated task. I must admit that I haven’t dived into the intricacies of git submodules, I just use them because they seem to be the best solution to integrate in a git-like way third-party code into a git project. But I can imagine that this functionality makes life much more difficult for the `GetGitRevisionDescription` script.

I’m going to look at the newest version of the script.

**Pull request merged**
